<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Peserta;

class PesertaSeeder extends Seeder
{
    public function run(): void
    {
        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '1234567890123456',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 1,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '0987654321123456',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 2,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '1122334455667788',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 3,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '2233445566778899',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 4,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '3344556677889900',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 5,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '4455667788990011',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 6,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '5566778899001122',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 7,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '6677889900112233',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 8,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '7788990011223344',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 9,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '8899001122334455',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 10,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,

        ]);
        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '9900112233445566',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 11,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '1011121314151617',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 12,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '1718192021222324',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 13,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '2425262728293031',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 14,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '3132333435363738',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 15,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '3930414243444546',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 16,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '4748495051525354',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 17,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '5556575859606162',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 18,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '6364656667686970',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 19,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '7172737475767778',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 20,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '7980818283848586',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 21,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '8788899091929394',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 22,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '9596979899101112',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 23,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '1314151617181920',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 24,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '2122232425262728',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 25,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '2930313233343536',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 26,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '3738394041424344',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 27,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '4546474849505152',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 28,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '5354555657585960',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 29,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);Peserta::create([
            'nama' => 'geminiraka',
            'jenis_kelamin' => 'putra',
            'nik' => '6162636465666768',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 30,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '6970717273747576',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 31,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

        Peserta::create([
            'nama' => 'anjay',
            'jenis_kelamin' => 'putri',
            'nik' => '7778798081828384',
            'tempat_lahir' => 'Trenggalek',
            'tgl_lahir' => '2024-05-22',
            'alamat_ktp' => 'a',
            'alamat_domisili' => 'a',
            'utusan_id' => 1,
            'cabang_id' => 32,
            'kk_ktp' => 'fnfdjgdfjgfdnjfgjgdf',
            'pasfoto' => 'jfbhjffjgkfdfjjjjkdf',
            'user_id' => 2,
            'tahun_id' => 1,
        ]);

    }

}
